name: Notify Discord
on: [push]
jobs:
  Notify-Discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord
        if: success()
        uses: jackall3n/discord-message@v1.7
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "Hello, from Github"
          username: "Github"
          avatar: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
