name: Notify Discord
on: [push]
jobs:
  Notify-Discord:
    name: Notify Discord
    uses: discord-actions/message@v2
    with:
      webhookUrl: ${{ secrets.DISCORD_WEBHOOK_URL }}
      message: "Hello, from Github"
      username: "Github",
      avatar: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"
